#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { eligibleArchive, matchedNull, mean, median, percentile } from './ah037_4h_ema_rsi_pullback_reversal.mjs';
const COST=11, DOUBLE=22, H=18;
const day=t=>new Date(t).toISOString().slice(0,10), avg=a=>mean(a)||0;
const tr=(b,i)=>i?Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c)):b[0].h-b[0].l;
function atr(b,i){return i>=14?avg(Array.from({length:14},(_,k)=>tr(b,i-13+k))):null}
function bollWidth(b,i){if(i<19)return null;const c=b.slice(i-19,i+1).map(x=>x.c),m=avg(c),sd=Math.sqrt(avg(c.map(x=>(x-m)**2)));return m?4*sd/m:null}
const cache=new WeakMap();
function indicators(b){if(!cache.has(b))cache.set(b,{a:b.map((_,i)=>atr(b,i)),w:b.map((_,i)=>bollWidth(b,i))});return cache.get(b)}
export function squeeze(b,i,p=.2){if(i<141)return null;const z=indicators(b),prior=z.w.slice(i-121,i-1).filter(Number.isFinite),cut=percentile(prior,p),six=z.w.slice(i-6,i),a=z.a[i-1],atrHist=z.a.slice(i-60,i).filter(Number.isFinite);if(!(six.length===6&&six.every(x=>x!=null&&x<=cut)&&a<median(atrHist)))return null;const block=b.slice(i-6,i);return {a,high:Math.max(...block.map(x=>x.h)),low:Math.min(...block.map(x=>x.l))}}
export function simulate(b,signal,side){const entryI=signal.i+1,entry=b[entryI]?.o,stop=side==='LONG'?Math.max(signal.s.low,entry-1.5*signal.s.a):Math.min(signal.s.high,entry+1.5*signal.s.a);if(!(entry&&(side==='LONG'?stop<entry:stop>entry)))return null;const target=side==='LONG'?entry+2.5*(entry-stop):entry-2.5*(stop-entry),last=Math.min(b.length-1,entryI+H);for(let j=entryI;j<=last;j++){const st=side==='LONG'?b[j].l<=stop:b[j].h>=stop,ta=side==='LONG'?b[j].h>=target:b[j].l<=target;if(st||ta){const why=st&&ta?'AMBIGUOUS_ADVERSE':st?'STOP':'TARGET',x=st?stop:target;return done(x,j,why)}}return done(b[last].c,last,'TIMEOUT');function done(x,j,reason){return {entry:entry,exit:x,entryIndex:entryI,exitIndex:j,reason,bps:1e4*(side==='LONG'?(x-entry)/entry:(entry-x)/entry)}}}
export function generate(sym,bars,splitFor,p=.2){const out=[];let lock=-1;for(let i=141;i+H+1<bars.length;i++){if(i<=lock)continue;const s=squeeze(bars,i,p);if(!s)continue;let side=null;if(bars[i].c>s.high+.2*s.a)side='LONG';if(bars[i].c<s.low-.2*s.a)side='SHORT';if(!side)continue;const x=simulate(bars,{i,s},side);if(!x)continue;out.push({...x,symbol:sym,side,decisionIndex:i,entryTs:bars[x.entryIndex].ts,day:day(bars[x.entryIndex].ts),split:splitFor(bars[x.entryIndex].ts)});lock=x.exitIndex}return out}
export function stats(t,c=COST){const n=t.map(x=>x.bps-c);let cu=0,pk=0,dd=0;for(const x of n){cu+=x;pk=Math.max(pk,cu);dd=Math.min(dd,cu-pk)}return {n:t.length,symbols:new Set(t.map(x=>x.symbol)).size,days:new Set(t.map(x=>x.day)).size,net_mean_bps:mean(n),net_median_bps:median(n),win_rate_pct:n.length?100*n.filter(x=>x>0).length/n.length:null,p5_bps:percentile(n,.05),p95_bps:percentile(n,.95),net_total_bps:n.reduce((a,b)=>a+b,0),max_drawdown_bps:dd,exits:Object.fromEntries(['STOP','TARGET','TIMEOUT','AMBIGUOUS_ADVERSE'].map(k=>[k,t.filter(x=>x.reason===k).length]))}}
function remove(t,key,k=1){let a=[...t],r=[];while(k--&&a.length){const m={};for(const x of a)m[x[key]]=(m[x[key]]||0)+x.bps-COST;const z=Object.entries(m).sort((x,y)=>y[1]-x[1])[0][0];r.push(z);a=a.filter(x=>x[key]!==z)}return {removed:r,stats:stats(a)}}
function chronology1h(archive){let start=Infinity,end=-Infinity;for(const bars of Object.values(archive))for(const b of bars){start=Math.min(start,b.ts);end=Math.max(end,b.ts)}const step=3_600_000,count=Math.floor((end-start)/step)+1,trainEnd=start+Math.floor(count*.55)*step,validationEnd=trainEnd+Math.floor(count*.2)*step,holdoutEnd=validationEnd+Math.floor(count*.15)*step,splitFor=ts=>ts<trainEnd?'train':ts<validationEnd?'validation':ts<holdoutEnd?'holdout':'forward',expected=['train','validation','holdout','forward'].map(name=>Array.from({length:count},(_,i)=>start+i*step).filter(ts=>splitFor(ts)===name).length);return {start,end,count,expected,splitFor}}
function main(){const get=(n,d)=>{const i=process.argv.indexOf('--'+n);return i>=0?process.argv[i+1]:d},path=get('archive','/opt/botalin-edge/data/bars_xs/bars.json'),out=get('out','/opt/botalin-edge/data/ah039_1h_volatility_squeeze_breakout_2026-08-03'),raw=JSON.parse(readFileSync(path,'utf8')),arc=Object.fromEntries(Object.entries(raw).map(([s,a])=>[s,a.map(r=>({ts:+r[0],o:+r[1],h:+r[2],l:+r[3],c:+r[4],v:+r[5]}))])),time=chronology1h(arc),{eligible}=eligibleArchive(arc,time),build=p=>Object.entries(eligible).flatMap(([s,b])=>generate(s,b,time.splitFor,p)),all=build(.2),part=x=>all.filter(t=>t.split===x),ho=part('holdout'),fw=part('forward'),oos=[...ho,...fw],neigh=[.15,.25].map(p=>stats(build(p).filter(t=>t.split==='holdout'||t.split==='forward'))),by={};for(const t of oos)by[t.symbol]=(by[t.symbol]||0)+Math.abs(t.bps-COST);const total=Math.max(1,Object.values(by).reduce((a,b)=>a+b,0));const report={label:'DISCOVERY_NOT_PROOF',task:'TASK-AH-039',data:{source_symbols:Object.keys(arc).length,eligible_symbols:Object.keys(eligible).length,window:{start:new Date(time.start).toISOString(),end:new Date(time.end).toISOString()}},rule:'Bollinger20/2 width <= prior120 percentile for six completed bars, ATR below prior60 median, first +/-0.2 ATR next-bar break, next open, 2.5R, 18 bars',costs:{roundtrip_bps:COST,double_bps:DOUBLE},train:stats(part('train')),validation:stats(part('validation')),holdout:stats(ho),forward:stats(fw),combined_oos:stats(oos),null:matchedNull(oos,eligible),remove_best_symbol:remove(oos,'symbol'),remove_best_three:remove(oos,'symbol',3),remove_best_day:remove(oos,'day'),max_symbol_abs_share:Math.max(0,...Object.values(by).map(x=>x/total)),neighbours:neigh,overlap:{status:'UNAVAILABLE',note:'Rejected-family timestamp ledgers not retained with AH-005A.'}};const h=report.holdout,f=report.forward,c=report.combined_oos;report.verdict=(h.n<100||f.n<100||h.days<10||f.days<10||c.days<30)?'DATA_INADEQUATE':([h,f].some(x=>x.net_mean_bps<=0||x.net_median_bps<=0)||report.null.p_value>=.05?'OOS_FAIL_REJECT_FAMILY':(stats(oos,DOUBLE).net_median_bps<0||report.remove_best_symbol.stats.net_total_bps<=0||report.remove_best_day.stats.net_total_bps<=0||report.max_symbol_abs_share>.25||neigh.some(x=>x.net_median_bps<0)?'ROBUSTNESS_FAIL_DEPRIORITIZE':'CANDIDATE_PASSPORT_DRAFT'));writeFileSync(out+'.json',JSON.stringify(report,null,2)+'\n');writeFileSync(out+'.csv',['split,n,symbols,days,mean,median',...['train','validation','holdout','forward','combined_oos'].map(k=>{const s=report[k];return[k,s.n,s.symbols,s.days,s.net_mean_bps,s.net_median_bps].join(',')})].join('\n')+'\n');console.log(JSON.stringify({eligible:Object.keys(eligible).length,holdout:report.holdout,forward:report.forward,null:report.null,verdict:report.verdict},null,2))}
if(process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1])main();
