#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { eligibleArchive, matchedNull, mean, median, percentile } from './ah037_4h_ema_rsi_pullback_reversal.mjs';
const COST=11,DOUBLE=22,H=6,day=t=>new Date(t).toISOString().slice(0,10),avg=a=>mean(a)||0,cache=new WeakMap();
const tr=(b,i)=>i?Math.max(b[i].h-b[i].l,Math.abs(b[i].h-b[i-1].c),Math.abs(b[i].l-b[i-1].c)):b[0].h-b[0].l;
function indicators(b){if(!cache.has(b)){const a=b.map((_,i)=>i>=14?avg(Array.from({length:14},(_,k)=>tr(b,i-13+k))):null),r=b.map((_,i)=>{if(i<14)return null;let g=0,l=0;for(let j=i-13;j<=i;j++){const d=b[j].c-b[j-1].c;g+=Math.max(0,d);l+=Math.max(0,-d)}return l===0?100:100-100/(1+g/l)}),v=b.map((_,i)=>i>=20?avg(b.slice(i-20,i).map(x=>x.v)):null);cache.set(b,{a,r,v})}return cache.get(b)}
function chronology1h(archive){let start=Infinity,end=-Infinity;for(const bars of Object.values(archive))for(const b of bars){start=Math.min(start,b.ts);end=Math.max(end,b.ts)}const step=3_600_000,count=Math.floor((end-start)/step)+1,trainEnd=start+Math.floor(count*.55)*step,validationEnd=trainEnd+Math.floor(count*.2)*step,holdoutEnd=validationEnd+Math.floor(count*.15)*step,splitFor=ts=>ts<trainEnd?'train':ts<validationEnd?'validation':ts<holdoutEnd?'holdout':'forward',expected=['train','validation','holdout','forward'].map(n=>Array.from({length:count},(_,i)=>start+i*step).filter(ts=>splitFor(ts)===n).length);return {start,end,count,expected,splitFor}}
export function simulate(b,signal,side){const entryI=signal.i+2,entry=b[entryI]?.o,stop=side==='LONG'?b[signal.i].l-signal.a:b[signal.i].h+signal.a;if(!(entry&&(side==='LONG'?stop<entry:stop>entry)))return null;const r=Math.abs(entry-stop),pre=b[signal.i-5].c,target=side==='LONG'?Math.min(pre,entry+2*r):Math.max(pre,entry-2*r);if(!(side==='LONG'?target>entry:target<entry))return null;const last=Math.min(b.length-1,entryI+H);for(let j=entryI;j<=last;j++){const st=side==='LONG'?b[j].l<=stop:b[j].h>=stop,ta=side==='LONG'?b[j].h>=target:b[j].l<=target;if(st||ta){const reason=st&&ta?'AMBIGUOUS_ADVERSE':st?'STOP':'TARGET',exit=st?stop:target;return done(exit,j,reason)}}return done(b[last].c,last,'TIMEOUT');function done(exit,exitIndex,reason){return {entry,exit,entryIndex:entryI,exitIndex,reason,bps:1e4*(side==='LONG'?(exit-entry)/entry:(entry-exit)/entry)}}}
export function generate(symbol,b,btc,splitFor,threshold=2.5){const z=indicators(b),bz=btc&&indicators(btc),btcByTs=new Map((btc||[]).map((x,i)=>[x.ts,{x,i}])),out=[];let lock=-1;for(let i=20;i+H+2<b.length;i++){if(i<=lock||!z.a[i]||!z.v[i]||b[i].v<2*z.v[i])continue;const move=b[i].c-b[i-5].c,side=move<=-threshold*z.a[i]&&z.r[i]<25?'LONG':move>=threshold*z.a[i]&&z.r[i]>75?'SHORT':null;if(!side||Math.abs(move)>5*z.a[i])continue;const q=btcByTs.get(b[i].ts);if(q&&bz?.a[q.i]&&Math.abs(q.x.c-btc[q.i-5]?.c)>2*bz.a[q.i]&&((side==='LONG'&&q.x.c<btc[q.i-5].c)||(side==='SHORT'&&q.x.c>btc[q.i-5].c)))continue;const mid=(b[i].h+b[i].l)/2,confirm=b[i+1].c,ok=side==='LONG'?confirm>mid:confirm<mid;if(!ok)continue;const x=simulate(b,{i,a:z.a[i]},side);if(!x)continue;out.push({...x,symbol,side,decisionIndex:i,entryTs:b[x.entryIndex].ts,day:day(b[x.entryIndex].ts),split:splitFor(b[x.entryIndex].ts)});lock=x.exitIndex}return out}
export function stats(t,c=COST){const n=t.map(x=>x.bps-c);let cu=0,pk=0,dd=0;for(const x of n){cu+=x;pk=Math.max(pk,cu);dd=Math.min(dd,cu-pk)}return {n:t.length,symbols:new Set(t.map(x=>x.symbol)).size,days:new Set(t.map(x=>x.day)).size,net_mean_bps:mean(n),net_median_bps:median(n),win_rate_pct:n.length?100*n.filter(x=>x>0).length/n.length:null,p5_bps:percentile(n,.05),p95_bps:percentile(n,.95),net_total_bps:n.reduce((a,b)=>a+b,0),max_drawdown_bps:dd,exits:Object.fromEntries(['STOP','TARGET','TIMEOUT','AMBIGUOUS_ADVERSE'].map(k=>[k,t.filter(x=>x.reason===k).length]))}}
function remove(t,key){if(!t.length)return {removed:null,stats:stats([])};const sums={};for(const x of t)sums[x[key]]=(sums[x[key]]||0)+x.bps-COST;const removed=Object.entries(sums).sort((a,b)=>b[1]-a[1])[0][0];return {removed,stats:stats(t.filter(x=>x[key]!==removed))}}
function main(){const arg=(n,d)=>{const i=process.argv.indexOf('--'+n);return i<0?d:process.argv[i+1]},path=arg('archive','/opt/botalin-edge/data/bars_xs/bars.json'),out=arg('out','/opt/botalin-edge/data/ah040_1h_impulse_mean_reversion_2026-08-03'),raw=JSON.parse(readFileSync(path,'utf8')),arc=Object.fromEntries(Object.entries(raw).map(([s,a])=>[s,a.map(r=>({ts:+r[0],o:+r[1],h:+r[2],l:+r[3],c:+r[4],v:+r[5]}))])),time=chronology1h(arc),{eligible}=eligibleArchive(arc,time),btc=eligible.BTCUSDT||arc.BTCUSDT,build=x=>Object.entries(eligible).flatMap(([s,b])=>generate(s,b,btc,time.splitFor,x)),all=build(2.5),part=x=>all.filter(t=>t.split===x),ho=part('holdout'),fw=part('forward'),oos=[...ho,...fw],by={};for(const t of oos)by[t.symbol]=(by[t.symbol]||0)+Math.abs(t.bps-COST);const total=Math.max(1,Object.values(by).reduce((a,b)=>a+b,0)),neighbours=[2.25,2.75].map(x=>stats(build(x).filter(t=>t.split==='holdout'||t.split==='forward'))),report={label:'DISCOVERY_NOT_PROOF',task:'TASK-AH-040',data:{source_symbols:Object.keys(arc).length,eligible_symbols:Object.keys(eligible).length,window:{start:new Date(time.start).toISOString(),end:new Date(time.end).toISOString()}},rule:'1h 2.5 ATR/5-bar impulse, 2x prior20 volume, RSI14 extreme, next-bar midpoint confirmation, next-open entry, 1 ATR stop, earlier pre-impulse/2R target, 6-bar timeout',costs:{roundtrip_bps:COST,double_bps:DOUBLE},train:stats(part('train')),validation:stats(part('validation')),holdout:stats(ho),forward:stats(fw),combined_oos:stats(oos),null:matchedNull(oos,eligible),remove_best_symbol:remove(oos,'symbol'),remove_best_day:remove(oos,'day'),max_symbol_abs_share:Math.max(0,...Object.values(by).map(x=>x/total)),neighbours,overlap:{status:'UNAVAILABLE',note:'Rejected-family timestamp ledgers not retained with AH-005A.'}};const h=report.holdout,f=report.forward,c=report.combined_oos;report.verdict=(h.n<100||f.n<100||h.days<10||f.days<10||c.days<30)?'DATA_INADEQUATE':([h,f].some(x=>x.net_mean_bps<=0||x.net_median_bps<=0)||report.null.p_value>=.05?'OOS_FAIL_REJECT_FAMILY':(stats(oos,DOUBLE).net_median_bps<0||report.remove_best_symbol.stats.net_total_bps<=0||report.remove_best_day.stats.net_total_bps<=0||report.max_symbol_abs_share>.25||neighbours.some(x=>x.net_median_bps<0)?'ROBUSTNESS_FAIL_DEPRIORITIZE':'CANDIDATE_PASSPORT_DRAFT'));writeFileSync(out+'.json',JSON.stringify(report,null,2)+'\n');writeFileSync(out+'.csv',['split,n,symbols,days,mean,median',...['train','validation','holdout','forward','combined_oos'].map(k=>{const s=report[k];return[k,s.n,s.symbols,s.days,s.net_mean_bps,s.net_median_bps].join(',')})].join('\n')+'\n');console.log(JSON.stringify({eligible:Object.keys(eligible).length,holdout:report.holdout,forward:report.forward,null:report.null,verdict:report.verdict},null,2))}
if(process.argv[1]&&fileURLToPath(import.meta.url)===process.argv[1])main();
