const labels: Record<string, string> = {
  TELEGRAM: "Telegram",
  INSTAGRAM: "Instagram",
  THREADS: "Threads",
  VK: "VK",
  PRIMARY: "Главная",
  SECONDARY: "Вторичная",
  LOW: "Низкий",
  MEDIUM: "Средний",
  HIGH: "Высокий",
  CRITICAL: "Критический",
  NEW: "Новый",
  REVIEWED: "Просмотрен",
  ARCHIVED: "В архиве",
  DELETED: "Удален",
  DRAFT: "Черновик",
  READY: "Готово",
  PUBLISHED: "Опубликовано",
  PLANNED: "Запланировано",
  CANCELLED: "Отменено",
  FAILED: "Ошибка",
  TODO: "Нужно сделать",
  DONE: "Готово",
  SKIPPED: "Пропущено",
  ACTIVE: "Активно",
  COMPLETED: "Завершено",
  PAUSED: "На паузе",
  ASSISTANT: "PersonaOS",
  USER: "Автор",
  SYSTEM: "Система",
  CONNECTED: "Подключено",
  DISCONNECTED: "Не подключено",
  UNKNOWN: "Не указано",
  HAPPY: "Радость",
  SAD: "Грусть",
  SURPRISED: "Удивление",
  EXCITED: "Воодушевление",
  ANGRY: "Злость",
  THOUGHTFUL: "Задумчивость",
  PHOTO: "Фото",
  VIDEO: "Видео",
  VOICE: "Голос",
  TEXT: "Текст",
  LINK: "Ссылка",
  LOCATION: "Локация",
  MIXED: "Смешанный",
  SHORT: "Короткий",
  LONG: "Длинный",
  CAPTURE: "Capture",
  REFLECTION: "Рефлексия",
  STORY: "История",
  WRITING: "Текст",
  PUBLISHING: "Публикация",
  VALUE: "Ценность",
  BELIEF: "Убеждение",
  THEME: "Тема",
  TONE: "Голос",
  HUMOR: "Юмор",
  STYLE: "Стиль",
  TOPIC: "Тема",
  EMOTION: "Эмоция",
  DECISION_PATTERN: "Паттерн решений",
  FORBIDDEN_TOPIC: "Запрещенная тема",
  RELATED: "Связано",
  SIMILAR: "Похоже",
  FOLLOWUP: "Продолжение",
  CONTRADICTION: "Противоречие"
};

export function label(value?: string | null) {
  if (!value) return "";
  return labels[value] ?? value;
}
